### ISSUE TITLE
NET type System.DateTimeOffset cannot be mapped to a BsonValue.

### ISSUE THREAD

**Issue by vbharuwa** [ChangemakerStudios/serilog-sinks-mongodb#78]
**We are getting following error with following code**
  ILogger<MasterController> _logger = null;
 public MasterController(ILogger<MasterController> logger,)
        {
            _logger = logger; 
        }

 _logger.LogInformation("testc info");
  throw new Exception("test exceptiopn");

Following is the stacktrace: 

**2022-07-14T05:30:39.8837936Z Exception while emitting periodic batch from Serilog.Sinks.MongoDB.MongoDBSink: System.ArgumentException: .NET type System.DateTimeOffset cannot be mapped to a BsonValue.**
   at MongoDB.Bson.BsonTypeMapper.MapToBsonValue(Object value)
   at Serilog.Helpers.MongoDbDocumentHelpers.ToBsonValue(LogEventPropertyValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Serilog.Sinks.MongoDB.LogEntry.MapFrom(LogEvent logEvent)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWriteAsync(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()
The thread 0x6230 has exited with code 0 (0x0).
2022-07-14T05:31:19.8832536Z Exception while emitting periodic batch from Serilog.Sinks.MongoDB.MongoDBSink: System.ArgumentException: .NET type System.DateTimeOffset cannot be mapped to a BsonValue.
   at MongoDB.Bson.BsonTypeMapper.MapToBsonValue(Object value)
   at Serilog.Helpers.MongoDbDocumentHelpers.ToBsonValue(LogEventPropertyValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Serilog.Sinks.MongoDB.LogEntry.MapFrom(LogEvent logEvent)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWriteAsync(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()
The thread 0x1314 has exited with code 0 (0x0).
2022-07-14T05:32:39.8972089Z Exception while emitting periodic batch from Serilog.Sinks.MongoDB.MongoDBSink: System.ArgumentException: .NET type System.DateTimeOffset cannot be mapped to a BsonValue.
   at MongoDB.Bson.BsonTypeMapper.MapToBsonValue(Object value)
   at Serilog.Helpers.MongoDbDocumentHelpers.ToBsonValue(LogEventPropertyValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Serilog.Sinks.MongoDB.LogEntry.MapFrom(LogEvent logEvent)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWriteAsync(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()
The thread 0x1c98 has exited with code 0 (0x0).
2022-07-14T05:35:19.8991323Z Exception while emitting periodic batch from Serilog.Sinks.MongoDB.MongoDBSink: System.ArgumentException: .NET type System.DateTimeOffset cannot be mapped to a BsonValue.
   at MongoDB.Bson.BsonTypeMapper.MapToBsonValue(Object value)
   at Serilog.Helpers.MongoDbDocumentHelpers.ToBsonValue(LogEventPropertyValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Serilog.Sinks.MongoDB.LogEntry.MapFrom(LogEvent logEvent)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWriteAsync(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick() 

**How are we supposed to fix it?**

**Comment by wuzhenda** [comment]
refs:
[https://github.com/ChangemakerStudios/serilog-sinks-mongodb/issues/74](url)
